### ISSUE TITLE
MySQL Incorrect datetime value: '0000-00-00 00:00:00' 

### ISSUE THREAD

**Issue by rianrajagede** [fushar/regrader#80]
I got an issue about incorrect datetime value. I think it produces an error because MySQL version.

I solved this by change all default datetime values in two files below become NULL:
```
../application/controllers/Site.php
.../application/models/Submission_manager.php
```

but I doubt, is there any better solution?

**Comment by mamat-rahmat** [comment]
Since MYSQL 5.6, strict mode is default.

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict
> Strict mode affects whether the server permits '0000-00-00' as a valid date: If strict mode is not enabled, '0000-00-00' is permitted and inserts produce no warning. If strict mode is enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning.

One solution is to tell user to disable STRICT_TRANS_TABLES mode in mysql config file.
But, its wiser to change default datetime value to another value. It will make easier for user.
(Note that supported range for DATETIME is '1000-01-01 00:00:00' to '9999-12-31 23:59:59')

cc @fushar
